Repository NEO-TAT/tat-gogogo, pull requests merged in 2019-07, with the labels that each got.

#7 [feature] Add login api
  configs/config.json
  configs/configs.go
  configs/server.go
  consts/consts.go
  controllers/login/login.go
  crawler/portal/portal.go
  go.mod
  go.sum
  routes/router.go
  server/server.go
Labels: feature

#9 [Feature] Add ci
  .circleci/config.yml
Labels: Optimization

#11 [WIP] [Feature] add-ci-cd
  .circleci/config.yml
Labels: Optimization, pending

#12 [Feature] add-curriculum
  configs/config.json
  configs/configs.go
  controllers/curriculum/curriculum.go
  controllers/login/login.go
  crawler/curriculum/curriculum.go
  crawler/portal/portal.go
  go.mod
  go.sum
  routes/router.go
  server/server.go
  utilities/arrutil/arrutil.go
  utilities/decoder/decoder.go
Labels: feature
