Repository NEO-TAT/tat-gogogo, pull requests merged in 2019-08, with the labels that each got.

#19 [Refactor ] Rename usecase into useCase
  interface/controllers/courses/courses.go
  interface/controllers/curriculum/curriculum.go
  interface/controllers/login/login.go
  usecase/curriculum_usecase.go
  usecase/info_usecase.go
  usecase/result_usecase.go
Labels: refactor

#21 [Feature] Add license
  LICENSE
Labels: feature

#20 [Feature] add-readme
  README.md
Labels: feature

#23 [Fix] readme-format
  README.md
Labels: fix

#24 [Refactor] fix-json-format
  interface/controllers/courses/courses.go
  interface/controllers/curriculum/curriculum.go
Labels: refactor

#26 [FEAT] Pull Request | Issue Template
  .github/issue_template.md
  .github/pull_request_template.md
Labels: feature

#27 [Feature] Add JWT support
  app.go
  go.mod
  go.sum
  infrastructure/api/handler/courses_handler.go
  infrastructure/api/handler/curriculum_handler.go
  infrastructure/api/handler/login_handelr.go
  infrastructure/middleware/middleware.go
  infrastructure/router/router.go
  interface/controller/courses_controller.go
  interface/controller/curriculum_controller.go
  interface/controller/login_controller.go
  interface/controllers/courses/courses.go
  interface/controllers/curriculum/curriculum.go
  interface/controllers/login/login.go
  interface/routes/router.go
Labels: feature
